data:
  wrf_folder: '/home/wrf_data/'
  era_folder: '/home/era_data/'
  scatter_folder: '/home/scatter/'
  stations_folder: '/home/stations/'
  wrf_mean_path: "/home/metadata/means_dict"
  wrf_std_path: "/home/metadata/stds_dict"
  base_folder: '/home'
  logs_folder: "/home/logs/"
  wrf_variables: ['uvmet10', 'T2', 'SEAICE']

s2s:
  sequence_len: 4

train:
  max_epochs: 15
  scheduler_type: MultiStepLR
  lr: 0.0001

model_type: BERTunet
model_args:
  BERTunet:
    n_channels: 9
    n_classes: 3
    bilinear: True


betas:
  beta1: 1
  beta2: 10
  beta3_t2: 0
  beta3_w10: 0
  beta4: 2

run_config:
  run_mode: 'train'
  num_workers: 16
  batch_size: 10
  use_spatial_encoding: 1
  use_time_encoding: 1
  use_landmask: 1
  weighted_meaner: 1

loss_config:
  loss_kernel: 'gauss'
  k: 9

test_config:
  best_epoch_id: 12
  run_id: 71
  draw_plots: 1
  save_losses: 0
  save_outputs: 0

