data:
  start_date: '2019-01-01'
  end_date: '2023-08-09'
  wrf_folder: '/home/wrf_data/'
  era_folder: '/home/era_data/'
  scatter_folder: '/home/scatter/'
  stations_folder: '/home/stations/interp/'
  wrf_mean_path: "/home/metadata/means_dict"
  wrf_std_path: "/home/metadata/stds_dict"
  base_folder: '/home'
  logs_folder: "/home/logs/"
  wrf_variables: ['uvmet10', 'T2', 'SEAICE', 'HGT']
  era_variables: ['u10', 'v10', 't2m']

s2s:
  sequence_len: 4

train:
  max_epochs: 15
  scheduler_type: MultiStepLR
  lr: 0.0001

model_type: BERTunet_raw
model_args:
  BERTunet:
    n_channels: 9
    n_classes: 3
    bilinear: True
    h: 210
    w: 280
  DETrajGRU:
    encoder_cahnnels: 2 
  VSBERTunet:
    n_channels: 4
    n_classes: 3
    max_len: 24
    chan_factor: 2
    bilinear: True


betas:
  beta1: 1
  beta2: 0
  beta3_t2: 0
  beta3_w10: 0
  beta4: 0

run_config:
  run_mode: 'test'
  num_workers: 16
  batch_size: 16
  use_spatial_encoding: 1
  use_time_encoding: 1
  use_landmask: 0
  weighted_meaner: 1
  variable_sequence_length: 0

loss_config:
  loss_kernel: 'gauss'
  k: 9

test_config:
  fig_format: 'png'
  best_epoch_id: 12
  run_id: 9
  draw_plots: 1
  save_losses: 1
  save_outputs: 0

no_metadata: 1